// formFieldsConfig.js
const formFieldsConfig = {
    researchPaper: [
      { name: "fid", type: "text", label: "Faculty ID", required: true },
      { name: "designation", type: "text", label: "Designation", required: true },
      { name: "department", type: "text", label: "Department", required: true },
      { name: "paperTitle", type: "text", label: "Paper Title", required: true },
      { name: "firstAuthor", type: "text", label: "First Author", required: true },
      { name: "conferenceName", type: "text", label: "Conference Name", required: true },
      { name: "publisherName", type: "text", label: "Publisher Name", required: true },
      { name: "hasapproved", type: "text", label: "Approval Status", required: true },
      { name: "pdf", type: "file", label: "PDF Upload", required: true },
      { name: "Genre", type: "text", label: "Genre", required: true },
      { name: "insertion", type: "date", label: "Date of Insertion", required: true },
      { name: "token", type: "text", label: "Token", required: true },
      { name: "link", type: "url", label: "Paper Link", required: true },
    ],
  
    journal: [
      { name: "fid", type: "text", label: "Faculty ID", required: true },
      { name: "designation", type: "text", label: "Designation", required: true },
      { name: "department", type: "text", label: "Department", required: true },
      { name: "paperTitle", type: "text", label: "Paper Title", required: true },
      { name: "firstAuthor", type: "text", label: "First Author", required: true },
      { name: "link", type: "url", label: "Journal Link", required: true },
      { name: "hasapproved", type: "text", label: "Approval Status", required: true },
      { name: "pdf", type: "file", label: "PDF Upload", required: true },
      { name: "Genre", type: "text", label: "Genre", required: true },
      { name: "insertion", type: "date", label: "Date of Insertion", required: true },
      { name: "token", type: "text", label: "Token", required: true },
    ],
  
    patent: [
      { name: "token", type: "text", label: "Token", required: true },
      { name: "fid", type: "text", label: "Faculty ID", required: true },
      { name: "designation", type: "text", label: "Designation", required: true },
      { name: "department", type: "text", label: "Department", required: true },
      { name: "patentTitle", type: "text", label: "Patent Title", required: true },
      { name: "patentId", type: "text", label: "Patent ID", required: true },
      { name: "patentDate", type: "date", label: "Patent Date", required: true },
      { name: "pdf", type: "file", label: "PDF Upload", required: true },
      { name: "Genre", type: "text", label: "Genre", required: true },
      { name: "hasapproved", type: "text", label: "Approval Status", required: true },
      { name: "insertion", type: "date", label: "Date of Insertion", required: true },
      { name: "authors", type: "text", label: "Authors (comma-separated)", required: true },
    ],
  
    phd: [
      { name: "token", type: "text", label: "Token", required: true },
      { name: "fid", type: "text", label: "Faculty ID", required: true },
      { name: "designation", type: "text", label: "Designation", required: true },
      { name: "department", type: "text", label: "Department", required: true },
      { name: "Organisation", type: "text", label: "Organisation", required: true },
      { name: "location", type: "text", label: "Location", required: true },
      { name: "date", type: "text", label: "Date", required: true },
      { name: "Genre", type: "text", label: "Genre", required: true },
      { name: "pdf", type: "file", label: "PDF Upload", required: true },
      { name: "hasapproved", type: "text", label: "Approval Status", required: true },
      { name: "insertion", type: "date", label: "Date of Insertion", required: true },
    ],
  
    studyLeave: [
      { name: "token", type: "text", label: "Token", required: true },
      { name: "fid", type: "text", label: "Faculty ID", required: true },
      { name: "phdtitle", type: "text", label: "PhD Title", required: true },
      { name: "organisation", type: "text", label: "Organisation", required: true },
      { name: "place", type: "text", label: "Place", required: true },
      { name: "phdprogress", type: "text", label: "PhD Progress", required: true },
      { name: "designation", type: "text", label: "Designation", required: true },
      { name: "department", type: "text", label: "Department", required: true },
      { name: "startDate", type: "date", label: "Start Date", required: true },
      { name: "endDate", type: "date", label: "End Date", required: true },
      { name: "previousStudyLeave", type: "text", label: "Previous Study Leave", required: false },
      { name: "pdf", type: "file", label: "PDF Upload", required: true },
      { name: "hasapproved", type: "select", label: "Approval Status", required: true, options: ["Pending", "Approved", "Rejected"] },
      { name: "Genre", type: "text", label: "Genre", required: true },
      { name: "insertion", type: "date", label: "Date of Insertion", required: true },
    ],
  
    tada: [
      { name: "fid", type: "text", label: "Faculty ID", required: true },
      { name: "designation", type: "text", label: "Designation", required: true },
      { name: "department", type: "text", label: "Department", required: true },
      { name: "paperTitle", type: "text", label: "Paper Title", required: true },
      { name: "conferenceName", type: "text", label: "Conference Name", required: true },
      { name: "place", type: "text", label: "Place", required: true },
      { name: "presenter", type: "text", label: "Presenter", required: true },
      { name: "tada", type: "text", label: "TADA", required: true },
      { name: "hasapproved", type: "text", label: "Approval Status", required: true },
      { name: "pdf", type: "file", label: "PDF Upload", required: true },
      { name: "Genre", type: "text", label: "Genre", required: true },
      { name: "insertion", type: "date", label: "Date of Insertion", required: true },
      { name: "token", type: "text", label: "Token", required: true },
    ],

    conference :[
        { name: "fid", type: "text", label: "Faculty ID", required: true },
        { name: "designation", type: "text", label: "Designation", required: true },
        { name: "department", type: "text", label: "Department", required: true },
        { name: "paperTitle", type: "text", label: "Paper Title", required: true },
        { name: "firstAuthor", type: "text", label: "First Author", required: true },
        { name: "conferenceName", type: "text", label: "Conference Name", required: true },
        { name: "publisherName", type: "text", label: "Publisher Name", required: true },
        { name: "link", type: "url", label: "Paper Link", required: true },
        { name: "hasapproved", type: "text", label: "Approval Status", required: true },
        { name: "pdf", type: "file", label: "PDF Upload", required: true },
    ],
    travellingallowances:[
      { name: "fid", type: "text", label: "Faculty ID", required: true },
      { name: "designation", type: "text", label: "Designation", required: true },
      { name: "department", type: "text", label: "Department", required: true },
      { name: "paperTitle", type: "text", label: "Paper Title", required: true },
      { name: "conferenceName", type: "text", label: "Conference Name", required: true },
      { name: "place", type: "text", label: "Place", required: true },
      { name: "presenter", type: "text", label: "Presenter", required: true },
      { name: "tada", type: "text", label: "TADA", required: true },
      { name: "hasapproved", type: "text", label: "Approval Status", required: true },
      { name: "pdf", type: "file", label: "PDF Upload", required: true },
      { name: "Genre", type: "text", label: "Genre", required: true },
      { name: "insertion", type: "date", label: "Date of Insertion", required: true },
      { name: "token", type: "text", label: "Token", required: true },
    ]
  };
  
  export default formFieldsConfig;
  